version: "4.5.1"
services:
  backend:
    build: .
    ports:
      - 8000:8000
    volumes:
      - .:/app
    depends_on:
      - db

  db:
    image: arangodb
    restart: always:latest
    environment:
      ArangoDatabase: storefront
      ArangoUser: root
      ARANGO_ROOT_PASSWORD: root
    ports:
        - 8530:8529
