version: '3.8'
services:
  backend:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    depends_on:
      - db

  db:
    image: arangodb
    volumes:
      - ./db:/data/
    restart: always
    environment:
      ArangoDatabase: storefront
      ArangoUser: root
      ARANGO_ROOT_PASSWORD: root
    ports:
        - "8530:8529"